### ISSUE TITLE
Gradle Kotlin DSL Build

### ISSUE THREAD

**Issue by TheMrMilchmann** [TheMrMilchmann/lwjgl3#1]
_A few notes I wrote for myself. Some will probably used in discussions and (hopefully) the PR._

The Gradle buildscipts for LWJGL will be written in Kotlin for improved type-safety and IDE support.
_______________________

# Goals
The goal of this is to migrate the entire build logic from Ant to Gradle.

While this is effectively making the Ant build obsolete, I won't go ahead and remove it and I will leave this decision up for further discussion instead. However, if this gets merged, I would be in favor of removing the old build logic entirely since any other decision would lead to an increase in maintaince time required for the build process.

### Further implications

- I'm not confident in my knowledge about native compilation and linking processes, hence I did not port these tasks to use Gradle's native compilation tasks. Additionally Gradle's native code plugins are still incubating and subject to change. The current implementation of these tasks does some basic out-of-date checks and calls the compiler and linker via Gradle's `exec` (which is similar to Ant's exec task). In my opinion this is not blocking and a potential port should happen at a later point in time.

- ~Since most IDE's are capable of generating project files from Gradle build scripts, the `.idea` and `confg/ide/` folders are likely no longer required. Even if they turn out to be required for further configuration of a specific IDE it might still be better to provide this setup as part of the build _scripts.~

# Implementation

## Bindings
All binding definitions are located in the `build.gradle.kts` file sitting in the project's root directory. A binding definition contains **all information about a binding in one place**. (**This is subject to change and will need validation once Gradle 4.3 is out!**)

### A binding definition
- **id** the id of the binding
- **title** the title of the binding
Used in the respective Javadoc and POM (In the latter the core binding's title is replaced by `The LWJGL core library` and all other get mapped to the format `LWJGL - ${title} bindings`.
- **projectDescription** the project description of the binding
Used in the POM.
- **packageName** the name of the package in which the binding's code is located
- **platforms** the platforms for which this binding is available (*Optional; Defaults to ALL*)

#### Example
This is an example binding definition for the GLFW binding.

Property|Value
--|----
id|glfw
title|GLFW
projectDescription|An multi-platform library for OpenGL, OpenGL ES and Vulkan development on the desktop. It provides a simple API for creating windows, contexts and surfaces, receiving input and events.
packageName|org.lwjgl.glfw

### *Activating* a binding
All bindings are active per default (as set in the `gradle.properties`) file. This option may be overriden by changing the values in that file or through use of the respective command line options.

## Tasks
Every task used to build bindings is added **per binding**. The respective task names usually follow the format `${bindingID}-${taskName}` (e.g. `glfw-jar`, `opengl-uploadNative`). *Note: The LWJGL core tasks are prefixed with `lwjgl` instead of `core`.*

The unprefixed tasks (e.g. `jar`) serve as umbrella tasks and depend on all of their binding specific respective counterparts. Generally speaking, these umbrella tasks should always be used, however, there are a few scenarios during development where it might be more useful to invoke a binding specific task.

If a binding specific task is invoked the binding has not been been set active the task is simply skipped. (Alternatively an error could be thrown.)

### Compilation and linking of natives
The `:modules:core:compileNative` task is an empty task which does nothing by itself. It is only used as an umbrella task for all other `compileNative-${binding}` tasks that handle the native compilation process for the respective binding.
Splitting up the compilation of native libraries into several tasks allows for an more effective use of Gradle's task caching. (If for example the lmdb's natives have changed but stb's did not, there is no reason to rebuild stb. The required uptodate checks are made by Gradle when using appropriate annotations.)

# Risks and assumptions
- Since I do not have access to any AWS service, I could not fully test the implementation of the `uploadNatives` task.
- On on most Windows systems it will still be necessary to call `vcvarsall` files before running the native compilation tasks. However, I encountered a few cases in which Gradle did not pick up the environment created by the BATs. **This needs further investigation and quite possbily a fix before this can be merged.**

# TODO
- [ ] Generate separate jars per binding
- [ ] Move frequently used and complex task definitions (such as `uploadNative`) to `buildSrc`
- [ ] Cleanup NativeCompileSpecs and NativeBuildSpecs
Once specs for all platforms have been ported, it might make sense to unify them further to reduce the amount of boilderplate that would have to be written for each task.
- [ ] Test all the things!

**Comment by TheMrMilchmann** [comment]
Small update:

It looks like Gradle 4.3 is about to be released already but I don't think it contains the changes necessary to cleanup this properly. I'll have a more detailled look at it later.

**Comment by TheMrMilchmann** [comment]
TODO: Include the Remotery binding in build-bindings.gradle.kts

(The commit in which the binding was added: https://github.com/LWJGL/lwjgl3/commit/d462192facb939f43dc8bfa4ed5c5578d42b1eb)

**Comment by TheMrMilchmann** [comment]
Outdated. This does not reflect the current state. I'll open a new issue soon.
